name: CI
on:
  push:
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'
  pull_request:
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'
  schedule:
     - cron: "0 0 1 */3 *" # Every 3 months
  workflow_dispatch:
defaults:
  run:
    shell: bash -l {0}
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install conda environment
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: polyfun.yml
          cache-env: true
      - name: Test
        run: python test_polyfun.py
